//! Extension and path → bundled SVG icon paths (Tabler + Zed file_icons).
//!
//! Generated by `python scripts/generate_file_type_icons.py`. Do not edit by hand.

use std::collections::HashMap;
use std::path::Path;
use std::sync::OnceLock;

use files_fs::FileItemKind;

use crate::tabler_icons;

const DEFAULT_FILE: &str = "icons/file_icons/file.svg";
const DEFAULT_FOLDER: &str = tabler_icons::FOLDER;
const DEFAULT_SYMLINK: &str = tabler_icons::LINK;

pub const FALLBACK_FILE_ICON: &str = DEFAULT_FILE;

fn tabler_overrides() -> &'static HashMap<&'static str, &'static str> {
    static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    MAP.get_or_init(|| HashMap::from([
        ("7z", "icons/tabler/file-type-zip.svg"),
        ("bmp", "icons/tabler/file-type-bmp.svg"),
        ("c++", "icons/tabler/file-type-cpp.svg"),
        ("cc", "icons/tabler/file-type-cpp.svg"),
        ("cjs", "icons/tabler/file-type-js.svg"),
        ("cpp", "icons/tabler/file-type-cpp.svg"),
        ("cppm", "icons/tabler/file-type-cpp.svg"),
        ("css", "icons/tabler/file-type-css.svg"),
        ("csv", "icons/tabler/file-type-csv.svg"),
        ("cts", "icons/tabler/file-type-ts.svg"),
        ("cxx", "icons/tabler/file-type-cpp.svg"),
        ("doc", "icons/tabler/file-type-doc.svg"),
        ("docx", "icons/tabler/file-type-doc.svg"),
        ("gz", "icons/tabler/file-type-zip.svg"),
        ("h++", "icons/tabler/file-type-cpp.svg"),
        ("hh", "icons/tabler/file-type-cpp.svg"),
        ("hpp", "icons/tabler/file-type-cpp.svg"),
        ("htm", "icons/tabler/file-type-html.svg"),
        ("html", "icons/tabler/file-type-html.svg"),
        ("hxx", "icons/tabler/file-type-cpp.svg"),
        ("inl", "icons/tabler/file-type-cpp.svg"),
        ("ixx", "icons/tabler/file-type-cpp.svg"),
        ("jpeg", "icons/tabler/file-type-jpg.svg"),
        ("jpg", "icons/tabler/file-type-jpg.svg"),
        ("js", "icons/tabler/file-type-js.svg"),
        ("mjs", "icons/tabler/file-type-js.svg"),
        ("mts", "icons/tabler/file-type-ts.svg"),
        ("pcss", "icons/tabler/file-type-css.svg"),
        ("pdf", "icons/tabler/file-type-pdf.svg"),
        ("php", "icons/tabler/file-type-php.svg"),
        ("png", "icons/tabler/file-type-png.svg"),
        ("postcss", "icons/tabler/file-type-css.svg"),
        ("ppt", "icons/tabler/file-type-ppt.svg"),
        ("pptx", "icons/tabler/file-type-ppt.svg"),
        ("rar", "icons/tabler/file-type-zip.svg"),
        ("rs", "icons/tabler/file-type-rs.svg"),
        ("sql", "icons/tabler/file-type-sql.svg"),
        ("sqlite", "icons/tabler/file-type-sql.svg"),
        ("svg", "icons/tabler/file-type-svg.svg"),
        ("tar", "icons/tabler/file-type-zip.svg"),
        ("ts", "icons/tabler/file-type-ts.svg"),
        ("tsv", "icons/tabler/file-type-csv.svg"),
        ("tsx", "icons/tabler/file-type-ts.svg"),
        ("txt", "icons/tabler/file-type-txt.svg"),
        ("vue", "icons/tabler/file-type-vue.svg"),
        ("xls", "icons/tabler/file-type-xls.svg"),
        ("xlsx", "icons/tabler/file-type-xls.svg"),
        ("xml", "icons/tabler/file-type-xml.svg"),
        ("zip", "icons/tabler/file-type-zip.svg"),
    ]))
}

fn zed_icon_paths() -> &'static HashMap<&'static str, &'static str> {
    static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    MAP.get_or_init(|| HashMap::from([
        ("astro", "icons/file_icons/astro.svg"),
        ("audio", "icons/file_icons/audio.svg"),
        ("bicep", "icons/file_icons/file.svg"),
        ("bun", "icons/file_icons/bun.svg"),
        ("c", "icons/file_icons/c.svg"),
        ("cairo", "icons/file_icons/cairo.svg"),
        ("code", "icons/file_icons/code.svg"),
        ("coffeescript", "icons/file_icons/coffeescript.svg"),
        ("cpp", "icons/file_icons/cpp.svg"),
        ("crystal", "icons/file_icons/file.svg"),
        ("csharp", "icons/file_icons/file.svg"),
        ("csproj", "icons/file_icons/file.svg"),
        ("css", "icons/file_icons/css.svg"),
        ("cue", "icons/file_icons/file.svg"),
        ("dart", "icons/file_icons/dart.svg"),
        ("default", "icons/file_icons/file.svg"),
        ("diff", "icons/file_icons/diff.svg"),
        ("docker", "icons/file_icons/docker.svg"),
        ("document", "icons/file_icons/book.svg"),
        ("editorconfig", "icons/file_icons/editorconfig.svg"),
        ("elixir", "icons/file_icons/elixir.svg"),
        ("elm", "icons/file_icons/elm.svg"),
        ("erlang", "icons/file_icons/erlang.svg"),
        ("eslint", "icons/file_icons/eslint.svg"),
        ("font", "icons/file_icons/font.svg"),
        ("fsharp", "icons/file_icons/fsharp.svg"),
        ("fsproj", "icons/file_icons/file.svg"),
        ("gitlab", "icons/file_icons/gitlab.svg"),
        ("gleam", "icons/file_icons/gleam.svg"),
        ("go", "icons/file_icons/go.svg"),
        ("graphql", "icons/file_icons/graphql.svg"),
        ("haskell", "icons/file_icons/haskell.svg"),
        ("hcl", "icons/file_icons/hcl.svg"),
        ("helm", "icons/file_icons/helm.svg"),
        ("heroku", "icons/file_icons/heroku.svg"),
        ("html", "icons/file_icons/html.svg"),
        ("image", "icons/file_icons/image.svg"),
        ("ipynb", "icons/file_icons/jupyter.svg"),
        ("java", "icons/file_icons/java.svg"),
        ("javascript", "icons/file_icons/javascript.svg"),
        ("json", "icons/file_icons/code.svg"),
        ("julia", "icons/file_icons/julia.svg"),
        ("kdl", "icons/file_icons/kdl.svg"),
        ("kotlin", "icons/file_icons/kotlin.svg"),
        ("lock", "icons/file_icons/lock.svg"),
        ("log", "icons/file_icons/info.svg"),
        ("lua", "icons/file_icons/lua.svg"),
        ("luau", "icons/file_icons/luau.svg"),
        ("markdown", "icons/file_icons/book.svg"),
        ("metal", "icons/file_icons/metal.svg"),
        ("nim", "icons/file_icons/nim.svg"),
        ("nix", "icons/file_icons/nix.svg"),
        ("ocaml", "icons/file_icons/ocaml.svg"),
        ("odin", "icons/file_icons/odin.svg"),
        ("phoenix", "icons/file_icons/phoenix.svg"),
        ("php", "icons/file_icons/php.svg"),
        ("prettier", "icons/file_icons/prettier.svg"),
        ("prisma", "icons/file_icons/prisma.svg"),
        ("puppet", "icons/file_icons/puppet.svg"),
        ("python", "icons/file_icons/python.svg"),
        ("r", "icons/file_icons/r.svg"),
        ("react", "icons/file_icons/react.svg"),
        ("roc", "icons/file_icons/roc.svg"),
        ("ruby", "icons/file_icons/ruby.svg"),
        ("rust", "icons/file_icons/rust.svg"),
        ("sass", "icons/file_icons/sass.svg"),
        ("scala", "icons/file_icons/scala.svg"),
        ("settings", "icons/file_icons/settings.svg"),
        ("solidity", "icons/file_icons/file.svg"),
        ("storage", "icons/file_icons/database.svg"),
        ("stylelint", "icons/file_icons/javascript.svg"),
        ("surrealql", "icons/file_icons/surrealql.svg"),
        ("svelte", "icons/file_icons/html.svg"),
        ("swift", "icons/file_icons/swift.svg"),
        ("tcl", "icons/file_icons/tcl.svg"),
        ("template", "icons/file_icons/html.svg"),
        ("terminal", "icons/file_icons/terminal.svg"),
        ("terraform", "icons/file_icons/terraform.svg"),
        ("toml", "icons/file_icons/toml.svg"),
        ("typescript", "icons/file_icons/typescript.svg"),
        ("v", "icons/file_icons/v.svg"),
        ("vbproj", "icons/file_icons/file.svg"),
        ("vcs", "icons/file_icons/git.svg"),
        ("video", "icons/file_icons/video.svg"),
        ("vs_sln", "icons/file_icons/file.svg"),
        ("vs_suo", "icons/file_icons/file.svg"),
        ("vue", "icons/file_icons/vue.svg"),
        ("vyper", "icons/file_icons/vyper.svg"),
        ("wgsl", "icons/file_icons/wgsl.svg"),
        ("yaml", "icons/file_icons/yaml.svg"),
        ("zig", "icons/file_icons/zig.svg"),
    ]))
}

fn extension_to_icon_key() -> &'static HashMap<&'static str, &'static str> {
    static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();
    MAP.get_or_init(|| {
        let mut map = HashMap::new();
        map.insert("astro", "astro");
        map.insert("bak", "backup");
        map.insert("bicep", "bicep");
        map.insert("lockb", "bun");
        map.insert("c", "c");
        map.insert("h", "c");
        map.insert("cairo", "cairo");
        map.insert("handlebars", "code");
        map.insert("metadata", "code");
        map.insert("rkt", "code");
        map.insert("scm", "code");
        map.insert("coffee", "coffeescript");
        map.insert("cr", "crystal");
        map.insert("ecr", "crystal");
        map.insert("cs", "csharp");
        map.insert("csproj", "csproj");
        map.insert("css", "css");
        map.insert("pcss", "css");
        map.insert("postcss", "css");
        map.insert("cue", "cue");
        map.insert("dart", "dart");
        map.insert("diff", "diff");
        map.insert("editorconfig", "editorconfig");
        map.insert("eex", "elixir");
        map.insert("ex", "elixir");
        map.insert("exs", "elixir");
        map.insert("heex", "elixir");
        map.insert("leex", "elixir");
        map.insert("neex", "elixir");
        map.insert("elm", "elm");
        map.insert("otf", "font");
        map.insert("ttf", "font");
        map.insert("woff", "font");
        map.insert("woff2", "font");
        map.insert("fs", "fsharp");
        map.insert("fsproj", "fsproj");
        map.insert("gitlab-ci.yml", "gitlab");
        map.insert("gitlab-ci.yaml", "gitlab");
        map.insert("gleam", "gleam");
        map.insert("go", "go");
        map.insert("mod", "go");
        map.insert("work", "go");
        map.insert("gql", "graphql");
        map.insert("graphql", "graphql");
        map.insert("graphqls", "graphql");
        map.insert("hs", "haskell");
        map.insert("hcl", "hcl");
        map.insert("htm", "html");
        map.insert("html", "html");
        map.insert("ipynb", "ipynb");
        map.insert("java", "java");
        map.insert("cjs", "javascript");
        map.insert("js", "javascript");
        map.insert("mjs", "javascript");
        map.insert("json", "json");
        map.insert("jsonc", "json");
        map.insert("jl", "julia");
        map.insert("kdl", "kdl");
        map.insert("kt", "kotlin");
        map.insert("lock", "lock");
        map.insert("log", "log");
        map.insert("lua", "lua");
        map.insert("luau", "luau");
        map.insert("markdown", "markdown");
        map.insert("md", "markdown");
        map.insert("metal", "metal");
        map.insert("nim", "nim");
        map.insert("nims", "nim");
        map.insert("nimble", "nim");
        map.insert("nix", "nix");
        map.insert("ml", "ocaml");
        map.insert("mli", "ocaml");
        map.insert("mlx", "ocaml");
        map.insert("odin", "odin");
        map.insert("php", "php");
        map.insert("prisma", "prisma");
        map.insert("pp", "puppet");
        map.insert("py", "python");
        map.insert("r", "r");
        map.insert("R", "r");
        map.insert("cjsx", "react");
        map.insert("ctsx", "react");
        map.insert("jsx", "react");
        map.insert("mjsx", "react");
        map.insert("mtsx", "react");
        map.insert("tsx", "react");
        map.insert("roc", "roc");
        map.insert("rb", "ruby");
        map.insert("rs", "rust");
        map.insert("sass", "sass");
        map.insert("scss", "sass");
        map.insert("scala", "scala");
        map.insert("sc", "scala");
        map.insert("conf", "settings");
        map.insert("ini", "settings");
        map.insert("sol", "solidity");
        map.insert("surql", "surrealql");
        map.insert("svelte", "svelte");
        map.insert("swift", "swift");
        map.insert("tcl", "tcl");
        map.insert("hbs", "template");
        map.insert("plist", "template");
        map.insert("xml", "template");
        map.insert("tf", "terraform");
        map.insert("tfvars", "terraform");
        map.insert("toml", "toml");
        map.insert("cts", "typescript");
        map.insert("mts", "typescript");
        map.insert("ts", "typescript");
        map.insert("v", "v");
        map.insert("vsh", "v");
        map.insert("vv", "v");
        map.insert("vbproj", "vbproj");
        map.insert("avi", "video");
        map.insert("m4v", "video");
        map.insert("mkv", "video");
        map.insert("mov", "video");
        map.insert("mp4", "video");
        map.insert("webm", "video");
        map.insert("wmv", "video");
        map.insert("sln", "vs_sln");
        map.insert("suo", "vs_suo");
        map.insert("vue", "vue");
        map.insert("vy", "vyper");
        map.insert("vyi", "vyper");
        map.insert("wgsl", "wgsl");
        map.insert("yaml", "yaml");
        map.insert("yml", "yaml");
        map.insert("zig", "zig");
        map
    })
}

fn icon_path_for_key(key: &str) -> &'static str {
    zed_icon_paths().get(key).copied().unwrap_or(DEFAULT_FILE)
}

/// Resolve a file suffix (extension, compound suffix, or file name) to an SVG asset path.
pub fn svg_path_for_suffix(suffix: &str) -> &'static str {
    let suffix = suffix.trim();
    if suffix.is_empty() {
        return DEFAULT_FILE;
    }
    let lower = suffix.to_ascii_lowercase();
    if let Some(path) = tabler_overrides().get(lower.as_str()) {
        return path;
    }
    if let Some(key) = extension_to_icon_key().get(lower.as_str()) {
        return icon_path_for_key(key);
    }
    DEFAULT_FILE
}

/// Extension without leading dot, e.g. `"pdf"`.
pub fn svg_path_for_extension(ext: &str) -> &'static str {
    svg_path_for_suffix(ext)
}

fn suffix_candidates(path: &Path) -> Vec<String> {
    let mut out = Vec::new();
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        out.push(name.to_string());
        let mut rest = name;
        while let Some((_, suffix)) = rest.split_once('.') {
            out.push(suffix.to_string());
            rest = suffix;
        }
    }
    if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
        out.push(ext.to_string());
    }
    out
}

/// Best bundled icon for a filesystem path (folder, symlink, drive root, or file).
pub fn svg_path_for_path(path: &Path) -> &'static str {
    if path.as_os_str().is_empty() {
        return DEFAULT_FOLDER;
    }
    #[cfg(windows)]
    {
        let s = path.to_string_lossy();
        if s.len() == 3 && s.as_bytes()[1] == b':' && s.as_bytes()[2] == b'\\' {
            if s.starts_with('C') || s.starts_with('c') {
                return tabler_icons::BRAND_WINDOWS;
            }
            return tabler_icons::DATABASE;
        }
    }
    if path.is_dir() {
        return DEFAULT_FOLDER;
    }
    if path.is_symlink() {
        return DEFAULT_SYMLINK;
    }
    for suffix in suffix_candidates(path) {
        let candidate = svg_path_for_suffix(&suffix);
        if candidate != DEFAULT_FILE {
            return candidate;
        }
    }
    DEFAULT_FILE
}

pub fn svg_path_for_kind_and_extension(kind: FileItemKind, extension: Option<&str>) -> &'static str {
    match kind {
        FileItemKind::Folder => DEFAULT_FOLDER,
        FileItemKind::Symlink => DEFAULT_SYMLINK,
        _ => extension
            .filter(|e| !e.is_empty())
            .map(svg_path_for_extension)
            .unwrap_or(DEFAULT_FILE),
    }
}

