//! Per-asset icon colors for file list tiles (light + dark).
//!
//! Generated by `python scripts/generate_file_icon_colors.py`. Do not edit by hand.

use std::collections::HashMap;
use std::sync::OnceLock;

use gpui::{rgb, Hsla};

struct PalettePair {
    light: u32,
    dark: u32,
}

fn palettes() -> &'static HashMap<&'static str, PalettePair> {
    static MAP: OnceLock<HashMap<&'static str, PalettePair>> = OnceLock::new();
    MAP.get_or_init(|| {
        HashMap::from([
            (
                "icons/file_icons/ai.svg",
                PalettePair {
                    light: 0xC52525,
                    dark: 0xEBBABA,
                },
            ),
            (
                "icons/file_icons/archive.svg",
                PalettePair {
                    light: 0x25C554,
                    dark: 0xBAEBC8,
                },
            ),
            (
                "icons/file_icons/astro.svg",
                PalettePair {
                    light: 0x8225C5,
                    dark: 0xD7BAEB,
                },
            ),
            (
                "icons/file_icons/audio.svg",
                PalettePair {
                    light: 0xD81B60,
                    dark: 0xF0CAD8,
                },
            ),
            (
                "icons/file_icons/book.svg",
                PalettePair {
                    light: 0xC5B125,
                    dark: 0xEBE5BA,
                },
            ),
            (
                "icons/file_icons/bun.svg",
                PalettePair {
                    light: 0x25AAC5,
                    dark: 0xBAE3EB,
                },
            ),
            (
                "icons/file_icons/c.svg",
                PalettePair {
                    light: 0xC5257B,
                    dark: 0xEBBAD4,
                },
            ),
            (
                "icons/file_icons/cairo.svg",
                PalettePair {
                    light: 0x4DC525,
                    dark: 0xC6EBBA,
                },
            ),
            (
                "icons/file_icons/camera.svg",
                PalettePair {
                    light: 0x2C25C5,
                    dark: 0xBCBAEB,
                },
            ),
            (
                "icons/file_icons/chevron_down.svg",
                PalettePair {
                    light: 0xC55A25,
                    dark: 0xEBCABA,
                },
            ),
            (
                "icons/file_icons/chevron_left.svg",
                PalettePair {
                    light: 0x25C589,
                    dark: 0xBAEBD9,
                },
            ),
            (
                "icons/file_icons/chevron_right.svg",
                PalettePair {
                    light: 0xB725C5,
                    dark: 0xE7BAEB,
                },
            ),
            (
                "icons/file_icons/chevron_up.svg",
                PalettePair {
                    light: 0xA3C525,
                    dark: 0xE1EBBA,
                },
            ),
            (
                "icons/file_icons/code.svg",
                PalettePair {
                    light: 0x2575C5,
                    dark: 0xBAD3EB,
                },
            ),
            (
                "icons/file_icons/coffeescript.svg",
                PalettePair {
                    light: 0xC52546,
                    dark: 0xEBBAC4,
                },
            ),
            (
                "icons/file_icons/conversations.svg",
                PalettePair {
                    light: 0x25C533,
                    dark: 0xBAEBBE,
                },
            ),
            (
                "icons/file_icons/cpp.svg",
                PalettePair {
                    light: 0x00897B,
                    dark: 0xD5EBE8,
                },
            ),
            (
                "icons/file_icons/css.svg",
                PalettePair {
                    light: 0x3949AB,
                    dark: 0x9AA4E1,
                },
            ),
            (
                "icons/file_icons/dart.svg",
                PalettePair {
                    light: 0x6125C5,
                    dark: 0xCCBAEB,
                },
            ),
            (
                "icons/file_icons/database.svg",
                PalettePair {
                    light: 0x00897B,
                    dark: 0xD5EBE8,
                },
            ),
            (
                "icons/file_icons/diff.svg",
                PalettePair {
                    light: 0xC59025,
                    dark: 0xEBDBBA,
                },
            ),
            (
                "icons/file_icons/docker.svg",
                PalettePair {
                    light: 0x039BE5,
                    dark: 0xCFE6F1,
                },
            ),
            (
                "icons/file_icons/editorconfig.svg",
                PalettePair {
                    light: 0x25C5BE,
                    dark: 0xBAEBE9,
                },
            ),
            (
                "icons/file_icons/elixir.svg",
                PalettePair {
                    light: 0xC5259C,
                    dark: 0xEBBADE,
                },
            ),
            (
                "icons/file_icons/elm.svg",
                PalettePair {
                    light: 0x6EC525,
                    dark: 0xD0EBBA,
                },
            ),
            (
                "icons/file_icons/erlang.svg",
                PalettePair {
                    light: 0x253FC5,
                    dark: 0xBAC2EB,
                },
            ),
            (
                "icons/file_icons/eslint.svg",
                PalettePair {
                    light: 0xC53925,
                    dark: 0xEBC0BA,
                },
            ),
            (
                "icons/file_icons/file.svg",
                PalettePair {
                    light: 0x546E7A,
                    dark: 0x6EAFCE,
                },
            ),
            (
                "icons/file_icons/folder.svg",
                PalettePair {
                    light: 0x43A047,
                    dark: 0x8ADC8E,
                },
            ),
            (
                "icons/file_icons/folder_open.svg",
                PalettePair {
                    light: 0x66BB6A,
                    dark: 0x7CE581,
                },
            ),
            (
                "icons/file_icons/font.svg",
                PalettePair {
                    light: 0x25C568,
                    dark: 0xBAEBCF,
                },
            ),
            (
                "icons/file_icons/fsharp.svg",
                PalettePair {
                    light: 0x9725C5,
                    dark: 0xDDBAEB,
                },
            ),
            (
                "icons/file_icons/git.svg",
                PalettePair {
                    light: 0xF4511E,
                    dark: 0xF3D6CC,
                },
            ),
            (
                "icons/file_icons/gitlab.svg",
                PalettePair {
                    light: 0xC4C525,
                    dark: 0xEBEBBA,
                },
            ),
            (
                "icons/file_icons/gleam.svg",
                PalettePair {
                    light: 0x2596C5,
                    dark: 0xBADDEB,
                },
            ),
            (
                "icons/file_icons/go.svg",
                PalettePair {
                    light: 0x00ACC1,
                    dark: 0xD2EBEE,
                },
            ),
            (
                "icons/file_icons/graphql.svg",
                PalettePair {
                    light: 0xC52567,
                    dark: 0xEBBACE,
                },
            ),
            (
                "icons/file_icons/hash.svg",
                PalettePair {
                    light: 0x38C525,
                    dark: 0xC0EBBA,
                },
            ),
            (
                "icons/file_icons/haskell.svg",
                PalettePair {
                    light: 0x4025C5,
                    dark: 0xC2BAEB,
                },
            ),
            (
                "icons/file_icons/hcl.svg",
                PalettePair {
                    light: 0xC56F25,
                    dark: 0xEBD1BA,
                },
            ),
            (
                "icons/file_icons/helm.svg",
                PalettePair {
                    light: 0x25C59D,
                    dark: 0xBAEBDF,
                },
            ),
            (
                "icons/file_icons/heroku.svg",
                PalettePair {
                    light: 0xC525BD,
                    dark: 0xEBBAE9,
                },
            ),
            (
                "icons/file_icons/html.svg",
                PalettePair {
                    light: 0xE65100,
                    dark: 0xF1DBCF,
                },
            ),
            (
                "icons/file_icons/image.svg",
                PalettePair {
                    light: 0xFFB300,
                    dark: 0xF2E7CE,
                },
            ),
            (
                "icons/file_icons/info.svg",
                PalettePair {
                    light: 0x8FC525,
                    dark: 0xDAEBBA,
                },
            ),
            (
                "icons/file_icons/java.svg",
                PalettePair {
                    light: 0xE53935,
                    dark: 0xF3C7C6,
                },
            ),
            (
                "icons/file_icons/javascript.svg",
                PalettePair {
                    light: 0xF9A825,
                    dark: 0xF4E5CC,
                },
            ),
            (
                "icons/file_icons/julia.svg",
                PalettePair {
                    light: 0x2560C5,
                    dark: 0xBACCEB,
                },
            ),
            (
                "icons/file_icons/jupyter.svg",
                PalettePair {
                    light: 0xC52532,
                    dark: 0xEBBABE,
                },
            ),
            (
                "icons/file_icons/kdl.svg",
                PalettePair {
                    light: 0x25C547,
                    dark: 0xBAEBC5,
                },
            ),
            (
                "icons/file_icons/kotlin.svg",
                PalettePair {
                    light: 0x7625C5,
                    dark: 0xD3BAEB,
                },
            ),
            (
                "icons/file_icons/lock.svg",
                PalettePair {
                    light: 0xC5A425,
                    dark: 0xEBE1BA,
                },
            ),
            (
                "icons/file_icons/lua.svg",
                PalettePair {
                    light: 0x25B6C5,
                    dark: 0xBAE6EB,
                },
            ),
            (
                "icons/file_icons/luau.svg",
                PalettePair {
                    light: 0xC52588,
                    dark: 0xEBBAD8,
                },
            ),
            (
                "icons/file_icons/magnifying_glass.svg",
                PalettePair {
                    light: 0x59C525,
                    dark: 0xCAEBBA,
                },
            ),
            (
                "icons/file_icons/metal.svg",
                PalettePair {
                    light: 0x252BC5,
                    dark: 0xBABCEB,
                },
            ),
            (
                "icons/file_icons/nim.svg",
                PalettePair {
                    light: 0xC54E25,
                    dark: 0xEBC7BA,
                },
            ),
            (
                "icons/file_icons/nix.svg",
                PalettePair {
                    light: 0x25C57C,
                    dark: 0xBAEBD5,
                },
            ),
            (
                "icons/file_icons/notebook.svg",
                PalettePair {
                    light: 0xAB25C5,
                    dark: 0xE3BAEB,
                },
            ),
            (
                "icons/file_icons/ocaml.svg",
                PalettePair {
                    light: 0xB0C525,
                    dark: 0xE5EBBA,
                },
            ),
            (
                "icons/file_icons/odin.svg",
                PalettePair {
                    light: 0x2581C5,
                    dark: 0xBAD6EB,
                },
            ),
            (
                "icons/file_icons/package.svg",
                PalettePair {
                    light: 0xC52553,
                    dark: 0xEBBAC8,
                },
            ),
            (
                "icons/file_icons/phoenix.svg",
                PalettePair {
                    light: 0x25C526,
                    dark: 0xBAEBBA,
                },
            ),
            (
                "icons/file_icons/php.svg",
                PalettePair {
                    light: 0x777BB4,
                    dark: 0x6770E3,
                },
            ),
            (
                "icons/file_icons/plus.svg",
                PalettePair {
                    light: 0x5525C5,
                    dark: 0xC9BAEB,
                },
            ),
            (
                "icons/file_icons/prettier.svg",
                PalettePair {
                    light: 0xC58325,
                    dark: 0xEBD7BA,
                },
            ),
            (
                "icons/file_icons/prisma.svg",
                PalettePair {
                    light: 0x25C5B2,
                    dark: 0xBAEBE5,
                },
            ),
            (
                "icons/file_icons/project.svg",
                PalettePair {
                    light: 0xC525A9,
                    dark: 0xEBBAE2,
                },
            ),
            (
                "icons/file_icons/puppet.svg",
                PalettePair {
                    light: 0x7AC525,
                    dark: 0xD4EBBA,
                },
            ),
            (
                "icons/file_icons/python.svg",
                PalettePair {
                    light: 0x306998,
                    dark: 0xA1C3DE,
                },
            ),
            (
                "icons/file_icons/r.svg",
                PalettePair {
                    light: 0x254CC5,
                    dark: 0xBAC6EB,
                },
            ),
            (
                "icons/file_icons/react.svg",
                PalettePair {
                    light: 0xC52D25,
                    dark: 0xEBBDBA,
                },
            ),
            (
                "icons/file_icons/replace.svg",
                PalettePair {
                    light: 0x25C55B,
                    dark: 0xBAEBCB,
                },
            ),
            (
                "icons/file_icons/replace_all.svg",
                PalettePair {
                    light: 0x8A25C5,
                    dark: 0xD9BAEB,
                },
            ),
            (
                "icons/file_icons/replace_next.svg",
                PalettePair {
                    light: 0xC5B925,
                    dark: 0xEBE7BA,
                },
            ),
            (
                "icons/file_icons/roc.svg",
                PalettePair {
                    light: 0x25A2C5,
                    dark: 0xBAE0EB,
                },
            ),
            (
                "icons/file_icons/ruby.svg",
                PalettePair {
                    light: 0xCC342D,
                    dark: 0xEAB3B1,
                },
            ),
            (
                "icons/file_icons/rust.svg",
                PalettePair {
                    light: 0xDEA584,
                    dark: 0xF4BA99,
                },
            ),
            (
                "icons/file_icons/sass.svg",
                PalettePair {
                    light: 0xC52574,
                    dark: 0xEBBAD2,
                },
            ),
            (
                "icons/file_icons/scala.svg",
                PalettePair {
                    light: 0x45C525,
                    dark: 0xC4EBBA,
                },
            ),
            (
                "icons/file_icons/settings.svg",
                PalettePair {
                    light: 0x3425C5,
                    dark: 0xBFBAEB,
                },
            ),
            (
                "icons/file_icons/surrealql.svg",
                PalettePair {
                    light: 0xC56225,
                    dark: 0xEBCDBA,
                },
            ),
            (
                "icons/file_icons/swift.svg",
                PalettePair {
                    light: 0x25C591,
                    dark: 0xBAEBDB,
                },
            ),
            (
                "icons/file_icons/tcl.svg",
                PalettePair {
                    light: 0xBF25C5,
                    dark: 0xE9BAEB,
                },
            ),
            (
                "icons/file_icons/terminal.svg",
                PalettePair {
                    light: 0x43A047,
                    dark: 0x8ADC8E,
                },
            ),
            (
                "icons/file_icons/terraform.svg",
                PalettePair {
                    light: 0x9BC525,
                    dark: 0xDEEBBA,
                },
            ),
            (
                "icons/file_icons/toml.svg",
                PalettePair {
                    light: 0x256DC5,
                    dark: 0xBAD0EB,
                },
            ),
            (
                "icons/file_icons/typescript.svg",
                PalettePair {
                    light: 0x1565C0,
                    dark: 0xD0DFF0,
                },
            ),
            (
                "icons/file_icons/v.svg",
                PalettePair {
                    light: 0xC5253E,
                    dark: 0xEBBAC2,
                },
            ),
            (
                "icons/file_icons/video.svg",
                PalettePair {
                    light: 0xF4511E,
                    dark: 0xF3D6CC,
                },
            ),
            (
                "icons/file_icons/vue.svg",
                PalettePair {
                    light: 0x42B883,
                    dark: 0x92E2BE,
                },
            ),
            (
                "icons/file_icons/vyper.svg",
                PalettePair {
                    light: 0x25C53A,
                    dark: 0xBAEBC1,
                },
            ),
            (
                "icons/file_icons/wgsl.svg",
                PalettePair {
                    light: 0x6925C5,
                    dark: 0xCFBAEB,
                },
            ),
            (
                "icons/file_icons/yaml.svg",
                PalettePair {
                    light: 0xC59825,
                    dark: 0xEBDDBA,
                },
            ),
            (
                "icons/file_icons/zig.svg",
                PalettePair {
                    light: 0x25C3C5,
                    dark: 0xBAEAEB,
                },
            ),
            (
                "icons/tabler/binary.svg",
                PalettePair {
                    light: 0x5E35B1,
                    dark: 0xB7A1E3,
                },
            ),
            (
                "icons/tabler/book.svg",
                PalettePair {
                    light: 0xC52594,
                    dark: 0xEBBADC,
                },
            ),
            (
                "icons/tabler/brand-windows.svg",
                PalettePair {
                    light: 0x66C525,
                    dark: 0xCEEBBA,
                },
            ),
            (
                "icons/tabler/database.svg",
                PalettePair {
                    light: 0x2537C5,
                    dark: 0xBAC0EB,
                },
            ),
            (
                "icons/tabler/file-certificate.svg",
                PalettePair {
                    light: 0xC54125,
                    dark: 0xEBC3BA,
                },
            ),
            (
                "icons/tabler/file-code.svg",
                PalettePair {
                    light: 0x25C570,
                    dark: 0xBAEBD1,
                },
            ),
            (
                "icons/tabler/file-music.svg",
                PalettePair {
                    light: 0xD81B60,
                    dark: 0xF0CAD8,
                },
            ),
            (
                "icons/tabler/file-settings.svg",
                PalettePair {
                    light: 0x9E25C5,
                    dark: 0xDFBAEB,
                },
            ),
            (
                "icons/tabler/file-text.svg",
                PalettePair {
                    light: 0xBCC525,
                    dark: 0xE8EBBA,
                },
            ),
            (
                "icons/tabler/file-type-bmp.svg",
                PalettePair {
                    light: 0x258EC5,
                    dark: 0xBADAEB,
                },
            ),
            (
                "icons/tabler/file-type-cpp.svg",
                PalettePair {
                    light: 0xC5255F,
                    dark: 0xEBBACC,
                },
            ),
            (
                "icons/tabler/file-type-css.svg",
                PalettePair {
                    light: 0x3949AB,
                    dark: 0x9AA4E1,
                },
            ),
            (
                "icons/tabler/file-type-csv.svg",
                PalettePair {
                    light: 0x31C525,
                    dark: 0xBEEBBA,
                },
            ),
            (
                "icons/tabler/file-type-doc.svg",
                PalettePair {
                    light: 0x4825C5,
                    dark: 0xC5BAEB,
                },
            ),
            (
                "icons/tabler/file-type-html.svg",
                PalettePair {
                    light: 0xE65100,
                    dark: 0xF1DBCF,
                },
            ),
            (
                "icons/tabler/file-type-jpg.svg",
                PalettePair {
                    light: 0xC57725,
                    dark: 0xEBD3BA,
                },
            ),
            (
                "icons/tabler/file-type-js.svg",
                PalettePair {
                    light: 0xF9A825,
                    dark: 0xF4E5CC,
                },
            ),
            (
                "icons/tabler/file-type-pdf.svg",
                PalettePair {
                    light: 0xE53935,
                    dark: 0xF3C7C6,
                },
            ),
            (
                "icons/tabler/file-type-php.svg",
                PalettePair {
                    light: 0x25C5A5,
                    dark: 0xBAEBE1,
                },
            ),
            (
                "icons/tabler/file-type-png.svg",
                PalettePair {
                    light: 0xC525B5,
                    dark: 0xEBBAE6,
                },
            ),
            (
                "icons/tabler/file-type-ppt.svg",
                PalettePair {
                    light: 0x87C525,
                    dark: 0xD8EBBA,
                },
            ),
            (
                "icons/tabler/file-type-rs.svg",
                PalettePair {
                    light: 0xDEA584,
                    dark: 0xF4BA99,
                },
            ),
            (
                "icons/tabler/file-type-sql.svg",
                PalettePair {
                    light: 0x2558C5,
                    dark: 0xBACAEB,
                },
            ),
            (
                "icons/tabler/file-type-svg.svg",
                PalettePair {
                    light: 0xC5252A,
                    dark: 0xEBBABC,
                },
            ),
            (
                "icons/tabler/file-type-ts.svg",
                PalettePair {
                    light: 0x1565C0,
                    dark: 0xD0DFF0,
                },
            ),
            (
                "icons/tabler/file-type-txt.svg",
                PalettePair {
                    light: 0x25C54F,
                    dark: 0xBAEBC7,
                },
            ),
            (
                "icons/tabler/file-type-vue.svg",
                PalettePair {
                    light: 0x7D25C5,
                    dark: 0xD5BAEB,
                },
            ),
            (
                "icons/tabler/file-type-xls.svg",
                PalettePair {
                    light: 0xC5AC25,
                    dark: 0xEBE3BA,
                },
            ),
            (
                "icons/tabler/file-type-xml.svg",
                PalettePair {
                    light: 0x25AFC5,
                    dark: 0xBAE4EB,
                },
            ),
            (
                "icons/tabler/file-type-zip.svg",
                PalettePair {
                    light: 0x6D4C41,
                    dark: 0xC98D79,
                },
            ),
            (
                "icons/tabler/file.svg",
                PalettePair {
                    light: 0x546E7A,
                    dark: 0x6EAFCE,
                },
            ),
            (
                "icons/tabler/folder-filled.svg",
                PalettePair {
                    light: 0x43A047,
                    dark: 0x8ADC8E,
                },
            ),
            (
                "icons/tabler/folder-open.svg",
                PalettePair {
                    light: 0x66BB6A,
                    dark: 0x7CE581,
                },
            ),
            (
                "icons/tabler/folder.svg",
                PalettePair {
                    light: 0x43A047,
                    dark: 0x8ADC8E,
                },
            ),
            (
                "icons/tabler/link.svg",
                PalettePair {
                    light: 0x8E24AA,
                    dark: 0xDDB7E6,
                },
            ),
            (
                "icons/tabler/photo.svg",
                PalettePair {
                    light: 0xFFB300,
                    dark: 0xF2E7CE,
                },
            ),
            (
                "icons/tabler/terminal-2.svg",
                PalettePair {
                    light: 0xC52580,
                    dark: 0xEBBAD6,
                },
            ),
            (
                "icons/tabler/video.svg",
                PalettePair {
                    light: 0xF4511E,
                    dark: 0xF3D6CC,
                },
            ),
        ])
    })
}

const DEFAULT: PalettePair = PalettePair {
    light: 0x546E7A,
    dark: 0x90A4AE,
};

fn pair_for_path(path: &str) -> &'static PalettePair {
    palettes().get(path).unwrap_or(&DEFAULT)
}

/// Tile background and icon foreground for a bundled SVG asset path.
pub fn tile_colors_for_svg_path(path: &str, is_dark: bool) -> (Hsla, Hsla) {
    let pair = pair_for_path(path);
    let fg: Hsla = rgb(if is_dark { pair.dark } else { pair.light }).into();
    let bg_opacity = if is_dark { 0.22 } else { 0.14 };
    (fg.opacity(bg_opacity), fg)
}
