#!/usr/bin/env python3
"""Generate per-icon light/dark palette for file list tiles."""

from __future__ import annotations

import colorsys
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
FILE_TYPE_ICONS = REPO / "crates" / "files-ui" / "src" / "file_type_icons.rs"
OUT = REPO / "crates" / "files-ui" / "src" / "file_type_icon_colors.rs"
FILE_ICONS_DIR = REPO / "crates" / "app-assets" / "assets" / "icons" / "file_icons"
TABLER_DIR = REPO / "crates" / "app-assets" / "assets" / "icons" / "tabler"

# Hand-tuned accents for common / structural icons (light hex). Dark is derived.
CURATED_LIGHT: dict[str, str] = {
    "icons/tabler/folder.svg": "#43A047",
    "icons/tabler/folder-filled.svg": "#43A047",
    "icons/tabler/folder-open.svg": "#66BB6A",
    "icons/tabler/link.svg": "#8E24AA",
    "icons/file_icons/folder.svg": "#43A047",
    "icons/file_icons/folder_open.svg": "#66BB6A",
    "icons/file_icons/file.svg": "#546E7A",
    "icons/tabler/file.svg": "#546E7A",
    "icons/tabler/file-type-pdf.svg": "#E53935",
    "icons/tabler/file-type-html.svg": "#E65100",
    "icons/tabler/file-type-js.svg": "#F9A825",
    "icons/tabler/file-type-ts.svg": "#1565C0",
    "icons/tabler/file-type-css.svg": "#3949AB",
    "icons/tabler/file-type-rs.svg": "#DEA584",
    "icons/tabler/file-type-py.svg": "#306998",
    "icons/tabler/file-music.svg": "#D81B60",
    "icons/tabler/video.svg": "#F4511E",
    "icons/tabler/binary.svg": "#5E35B1",
    "icons/tabler/photo.svg": "#FFB300",
    "icons/tabler/file-zip.svg": "#6D4C41",
    "icons/tabler/file-type-zip.svg": "#6D4C41",
    "icons/file_icons/rust.svg": "#DEA584",
    "icons/file_icons/python.svg": "#306998",
    "icons/file_icons/javascript.svg": "#F9A825",
    "icons/file_icons/typescript.svg": "#1565C0",
    "icons/file_icons/go.svg": "#00ACC1",
    "icons/file_icons/java.svg": "#E53935",
    "icons/file_icons/cpp.svg": "#00897B",
    "icons/file_icons/html.svg": "#E65100",
    "icons/file_icons/css.svg": "#3949AB",
    "icons/file_icons/json.svg": "#FDD835",
    "icons/file_icons/docker.svg": "#039BE5",
    "icons/file_icons/git.svg": "#F4511E",
    "icons/file_icons/markdown.svg": "#546E7A",
    "icons/file_icons/ruby.svg": "#CC342D",
    "icons/file_icons/php.svg": "#777BB4",
    "icons/file_icons/vue.svg": "#42B883",
    "icons/file_icons/audio.svg": "#D81B60",
    "icons/file_icons/video.svg": "#F4511E",
    "icons/file_icons/image.svg": "#FFB300",
    "icons/file_icons/database.svg": "#00897B",
    "icons/file_icons/terminal.svg": "#43A047",
}


def parse_hex(hex_color: str) -> tuple[float, float, float]:
    h = hex_color.lstrip("#")
    r = int(h[0:2], 16) / 255.0
    g = int(h[2:4], 16) / 255.0
    b = int(h[4:6], 16) / 255.0
    return r, g, b


def to_hex(r: float, g: float, b: float) -> str:
    return "#{:02X}{:02X}{:02X}".format(
        int(max(0, min(1, r)) * 255),
        int(max(0, min(1, g)) * 255),
        int(max(0, min(1, b)) * 255),
    )


def rgb_u32(hex_color: str) -> int:
    h = hex_color.lstrip("#")
    return int(h, 16)


def dark_from_light(hex_light: str) -> str:
    """Lift and slightly boost saturation for dark UI backgrounds."""
    r, g, b = parse_hex(hex_light)
    h, s, l = colorsys.rgb_to_hls(r, g, b)
    s = min(1.0, s * 1.08 + 0.06)
    l = min(0.88, max(0.62, l * 0.45 + 0.52))
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return to_hex(r, g, b)


def golden_light_hex(index: int) -> str:
    hue = (index * 137.508) % 360
    r, g, b = colorsys.hls_to_rgb(hue / 360.0, 0.46, 0.68)
    return to_hex(r, g, b)


def collect_svg_paths() -> list[str]:
    paths: set[str] = set()
    if FILE_TYPE_ICONS.is_file():
        text = FILE_TYPE_ICONS.read_text(encoding="utf-8")
        for match in re.findall(r'"((?:icons/file_icons|icons/tabler)/[^"]+\.svg)"', text):
            paths.add(match)
    for svg in FILE_ICONS_DIR.glob("*.svg"):
        paths.add(f"icons/file_icons/{svg.name}")
    for name in (
        "folder.svg",
        "folder-filled.svg",
        "folder-open.svg",
        "link.svg",
        "file.svg",
        "file-music.svg",
        "video.svg",
        "binary.svg",
        "photo.svg",
        "database.svg",
        "book.svg",
        "terminal-2.svg",
        "file-settings.svg",
        "file-certificate.svg",
        "brand-windows.svg",
    ):
        p = TABLER_DIR / name
        if p.is_file():
            paths.add(f"icons/tabler/{name}")
    return sorted(paths)


def emit(paths: list[str]) -> None:
    lines = [
        "//! Per-asset icon colors for file list tiles (light + dark).",
        "//!",
        "//! Generated by `python scripts/generate_file_icon_colors.py`. Do not edit by hand.",
        "",
        "use std::collections::HashMap;",
        "use std::sync::OnceLock;",
        "",
        "use gpui::{Hsla, rgb};",
        "",
        "struct PalettePair {",
        "    light: u32,",
        "    dark: u32,",
        "}",
        "",
        "fn palettes() -> &'static HashMap<&'static str, PalettePair> {",
        "    static MAP: OnceLock<HashMap<&'static str, PalettePair>> = OnceLock::new();",
        "    MAP.get_or_init(|| HashMap::from([",
    ]
    auto_index = 0
    for path in paths:
        if path in CURATED_LIGHT:
            light = CURATED_LIGHT[path]
        else:
            light = golden_light_hex(auto_index)
            auto_index += 1
        dark = dark_from_light(light)
        lines.append(
            f'        ("{path}", PalettePair {{ light: 0x{rgb_u32(light):06X}, dark: 0x{rgb_u32(dark):06X} }}),'
        )
    lines.extend(
        [
            "    ]))",
            "}",
            "",
            "const DEFAULT: PalettePair = PalettePair {",
            "    light: 0x546E7A,",
            "    dark: 0x90A4AE,",
            "};",
            "",
            "fn pair_for_path(path: &str) -> &'static PalettePair {",
            "    palettes().get(path).unwrap_or(&DEFAULT)",
            "}",
            "",
            "/// Tile background and icon foreground for a bundled SVG asset path.",
            "pub fn tile_colors_for_svg_path(path: &str, is_dark: bool) -> (Hsla, Hsla) {",
            "    let pair = pair_for_path(path);",
            "    let fg: Hsla = rgb(if is_dark { pair.dark } else { pair.light }).into();",
            "    let bg_opacity = if is_dark { 0.22 } else { 0.14 };",
            "    (fg.opacity(bg_opacity), fg)",
            "}",
            "",
        ]
    )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    paths = collect_svg_paths()
    emit(paths)
    print(f"Wrote {OUT} ({len(paths)} icon palettes)")


if __name__ == "__main__":
    main()
