#!/usr/bin/env python3
"""Generate files-ui file_type_icons.rs from Zed icon_theme mappings + Tabler overrides."""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ZED_ICON_THEME = REPO.parent / "zed" / "crates" / "theme" / "src" / "icon_theme.rs"
OUT = REPO / "crates" / "files-ui" / "src" / "file_type_icons.rs"
FILE_ICONS_DIR = REPO / "crates" / "app-assets" / "assets" / "icons" / "file_icons"

# Tabler outline file-type icons (see scripts/sync_tabler_icons.py).
TABLER_OVERRIDES: dict[str, str] = {
    "pdf": "icons/tabler/file-type-pdf.svg",
    "htm": "icons/tabler/file-type-html.svg",
    "html": "icons/tabler/file-type-html.svg",
    "js": "icons/tabler/file-type-js.svg",
    "mjs": "icons/tabler/file-type-js.svg",
    "cjs": "icons/tabler/file-type-js.svg",
    "ts": "icons/tabler/file-type-ts.svg",
    "tsx": "icons/tabler/file-type-ts.svg",
    "mts": "icons/tabler/file-type-ts.svg",
    "cts": "icons/tabler/file-type-ts.svg",
    "css": "icons/tabler/file-type-css.svg",
    "pcss": "icons/tabler/file-type-css.svg",
    "postcss": "icons/tabler/file-type-css.svg",
    "xml": "icons/tabler/file-type-xml.svg",
    "sql": "icons/tabler/file-type-sql.svg",
    "sqlite": "icons/tabler/file-type-sql.svg",
    "doc": "icons/tabler/file-type-doc.svg",
    "docx": "icons/tabler/file-type-doc.svg",
    "xls": "icons/tabler/file-type-xls.svg",
    "xlsx": "icons/tabler/file-type-xls.svg",
    "ppt": "icons/tabler/file-type-ppt.svg",
    "pptx": "icons/tabler/file-type-ppt.svg",
    "zip": "icons/tabler/file-type-zip.svg",
    "rar": "icons/tabler/file-type-zip.svg",
    "7z": "icons/tabler/file-type-zip.svg",
    "tar": "icons/tabler/file-type-zip.svg",
    "gz": "icons/tabler/file-type-zip.svg",
    "csv": "icons/tabler/file-type-csv.svg",
    "tsv": "icons/tabler/file-type-csv.svg",
    "jpg": "icons/tabler/file-type-jpg.svg",
    "jpeg": "icons/tabler/file-type-jpg.svg",
    "png": "icons/tabler/file-type-png.svg",
    "bmp": "icons/tabler/file-type-bmp.svg",
    "svg": "icons/tabler/file-type-svg.svg",
    "vue": "icons/tabler/file-type-vue.svg",
    "rs": "icons/tabler/file-type-rs.svg",
    "php": "icons/tabler/file-type-php.svg",
    "txt": "icons/tabler/file-type-txt.svg",
    "cpp": "icons/tabler/file-type-cpp.svg",
    "cc": "icons/tabler/file-type-cpp.svg",
    "cxx": "icons/tabler/file-type-cpp.svg",
    "hpp": "icons/tabler/file-type-cpp.svg",
    "c++": "icons/tabler/file-type-cpp.svg",
    "h++": "icons/tabler/file-type-cpp.svg",
    "hh": "icons/tabler/file-type-cpp.svg",
    "hxx": "icons/tabler/file-type-cpp.svg",
    "inl": "icons/tabler/file-type-cpp.svg",
    "ixx": "icons/tabler/file-type-cpp.svg",
    "cppm": "icons/tabler/file-type-cpp.svg",
}


def parse_zed_arrays(text: str) -> tuple[list[tuple[str, list[str]]], dict[str, str]]:
    suffix_block = re.search(
        r"const FILE_SUFFIXES_BY_ICON_KEY.*?=\s*&\[(.*?)\];",
        text,
        re.DOTALL,
    )
    icons_block = re.search(
        r"const FILE_ICONS.*?=\s*&\[(.*?)\];",
        text,
        re.DOTALL,
    )
    if not suffix_block or not icons_block:
        raise SystemExit("failed to parse Zed icon_theme.rs")

    suffixes: list[tuple[str, list[str]]] = []
    for key, exts_raw in re.findall(r'\("([^"]+)",\s*&\[(.*?)\]\)', suffix_block.group(1), re.DOTALL):
        exts = re.findall(r'"([^"]+)"', exts_raw)
        suffixes.append((key, exts))

    icons: dict[str, str] = {}
    for key, path in re.findall(r'\("([^"]+)",\s*"([^"]+)"\)', icons_block.group(1)):
        icons[key] = path

    return suffixes, icons


def normalize_zed_svgs() -> None:
    if not FILE_ICONS_DIR.is_dir():
        return
    for path in FILE_ICONS_DIR.glob("*.svg"):
        text = path.read_text(encoding="utf-8")
        updated = (
            text.replace('stroke="black"', 'stroke="currentColor"')
            .replace("stroke='black'", "stroke='currentColor'")
            .replace('fill="black"', 'fill="currentColor"')
            .replace("fill='black'", "fill='currentColor'")
        )
        if updated != text:
            path.write_text(updated, encoding="utf-8", newline="\n")


def emit(suffixes: list[tuple[str, list[str]]], icons: dict[str, str]) -> None:
    lines: list[str] = [
        "//! Extension and path → bundled SVG icon paths (Tabler + Zed file_icons).",
        "//!",
        "//! Generated by `python scripts/generate_file_type_icons.py`. Do not edit by hand.",
        "",
        "use std::collections::HashMap;",
        "use std::path::Path;",
        "use std::sync::OnceLock;",
        "",
        "use files_fs::FileItemKind;",
        "",
        "use crate::tabler_icons;",
        "",
        "const DEFAULT_FILE: &str = \"icons/file_icons/file.svg\";",
        "const DEFAULT_FOLDER: &str = tabler_icons::FOLDER;",
        "const DEFAULT_SYMLINK: &str = tabler_icons::LINK;",
        "",
        "pub const FALLBACK_FILE_ICON: &str = DEFAULT_FILE;",
        "",
        "fn tabler_overrides() -> &'static HashMap<&'static str, &'static str> {",
        "    static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();",
        "    MAP.get_or_init(|| HashMap::from([",
    ]
    for ext, path in sorted(TABLER_OVERRIDES.items()):
        lines.append(f'        ("{ext}", "{path}"),')
    lines.extend(
        [
            "    ]))",
            "}",
            "",
            "fn zed_icon_paths() -> &'static HashMap<&'static str, &'static str> {",
            "    static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();",
            "    MAP.get_or_init(|| HashMap::from([",
        ]
    )
    for key, path in sorted(icons.items()):
        lines.append(f'        ("{key}", "{path}"),')
    lines.extend(
        [
            "    ]))",
            "}",
            "",
            "fn extension_to_icon_key() -> &'static HashMap<&'static str, &'static str> {",
            "    static MAP: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();",
            "    MAP.get_or_init(|| {",
            "        let mut map = HashMap::new();",
        ]
    )
    for key, exts in suffixes:
        for ext in exts:
            lines.append(f'        map.insert("{ext}", "{key}");')
    lines.extend(
        [
            "        map",
            "    })",
            "}",
            "",
            "fn icon_path_for_key(key: &str) -> &'static str {",
            "    zed_icon_paths().get(key).copied().unwrap_or(DEFAULT_FILE)",
            "}",
            "",
            "/// Resolve a file suffix (extension, compound suffix, or file name) to an SVG asset path.",
            "pub fn svg_path_for_suffix(suffix: &str) -> &'static str {",
            "    let suffix = suffix.trim();",
            "    if suffix.is_empty() {",
            "        return DEFAULT_FILE;",
            "    }",
            "    let lower = suffix.to_ascii_lowercase();",
            "    if let Some(path) = tabler_overrides().get(lower.as_str()) {",
            "        return path;",
            "    }",
            "    if let Some(key) = extension_to_icon_key().get(lower.as_str()) {",
            "        return icon_path_for_key(key);",
            "    }",
            "    DEFAULT_FILE",
            "}",
            "",
            "/// Extension without leading dot, e.g. `\"pdf\"`.",
            "pub fn svg_path_for_extension(ext: &str) -> &'static str {",
            "    svg_path_for_suffix(ext)",
            "}",
            "",
            "fn suffix_candidates(path: &Path) -> Vec<String> {",
            "    let mut out = Vec::new();",
            "    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {",
            "        out.push(name.to_string());",
            "        let mut rest = name;",
            "        while let Some((_, suffix)) = rest.split_once('.') {",
            "            out.push(suffix.to_string());",
            "            rest = suffix;",
            "        }",
            "    }",
            "    if let Some(ext) = path.extension().and_then(|e| e.to_str()) {",
            "        out.push(ext.to_string());",
            "    }",
            "    out",
            "}",
            "",
            "/// Best bundled icon for a filesystem path (folder, symlink, drive root, or file).",
            "pub fn svg_path_for_path(path: &Path) -> &'static str {",
            "    if path.as_os_str().is_empty() {",
            "        return DEFAULT_FOLDER;",
            "    }",
            "    #[cfg(windows)]",
            "    {",
            "        let s = path.to_string_lossy();",
            "        if s.len() == 3 && s.as_bytes()[1] == b':' && s.as_bytes()[2] == b'\\\\' {",
            "            if s.starts_with('C') || s.starts_with('c') {",
            "                return tabler_icons::BRAND_WINDOWS;",
            "            }",
            "            return tabler_icons::DATABASE;",
            "        }",
            "    }",
            "    if path.is_dir() {",
            "        return DEFAULT_FOLDER;",
            "    }",
            "    if path.is_symlink() {",
            "        return DEFAULT_SYMLINK;",
            "    }",
            "    for suffix in suffix_candidates(path) {",
            "        let candidate = svg_path_for_suffix(&suffix);",
            "        if candidate != DEFAULT_FILE {",
            "            return candidate;",
            "        }",
            "    }",
            "    DEFAULT_FILE",
            "}",
            "",
            "pub fn svg_path_for_kind_and_extension(kind: FileItemKind, extension: Option<&str>) -> &'static str {",
            "    match kind {",
            "        FileItemKind::Folder => DEFAULT_FOLDER,",
            "        FileItemKind::Symlink => DEFAULT_SYMLINK,",
            "        _ => extension",
            "            .filter(|e| !e.is_empty())",
            "            .map(svg_path_for_extension)",
            "            .unwrap_or(DEFAULT_FILE),",
            "    }",
            "}",
            "",
        ]
    )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> None:
    text = ZED_ICON_THEME.read_text(encoding="utf-8")
    suffixes, icons = parse_zed_arrays(text)
    normalize_zed_svgs()
    emit(suffixes, icons)
    print(f"Wrote {OUT} ({len(suffixes)} icon keys, {len(TABLER_OVERRIDES)} Tabler overrides)")


if __name__ == "__main__":
    main()
